export const newsData = [
  {
    id: 1,
    jobTitle: "Graphic Design",
    location: "Ilorin | Full-time",
    position: "Web Developer",
    standPoint: "Negotiable",
    remuneration: 400000,
    duration: "2 months ago",
    name: "Code Village Limited",
    specialization: "Software Development",
    address: "Ilorin, Nigeria",
    logo: "/cv.png",
    summary: "Job Summary",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsum estfugit excepturi modi iste, quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum voluptatesmollitia quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum  sapiente provident!",
    qualification: "Diploma",
    level: "Mid level",
    experience: "4years",
  },
  {
    id: 2,
    jobTitle: "Chief Security Officer",
    location: "Lagos | Full-time",
    position: "Hotel and Hospitality",
    standPoint: "Negotiable",
    remuneration: 400000,
    duration: "2 months ago",
    name: "Oriental Hotel",
    specialization: "Hotel, Restaurant, Bar",
    address: "Lagos, Nigeria",
    logo: "/hotel.jpg",
    summary: "Job Summary",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsum estfugit excepturi modi iste, quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum voluptatesmollitia quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum  sapiente provident!",
    qualification: "Diploma",
    level: "Mid level",
    experience: "4years",
  },
  {
    id: 3,
    jobTitle: "Sales Manager",
    location: "Ilorin | Full-time",
    position: "Manager",
    standPoint: "Negotiable",
    remuneration: 400000,
    duration: "2 months ago",
    name: "Item7 Party Rice and Shawama",
    specialization: "Restaurant and Eatery",
    address: "Ilorin, Nigeria",
    logo: "/item7.png",
    summary: "Job Summary",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsum estfugit excepturi modi iste, quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum voluptatesmollitia quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum  sapiente provident!",
    qualification: "Diploma",
    level: "Mid level",
    experience: "4years",
  },
  {
    id: 4,
    jobTitle: "Sales Manager",
    location: "Ilorin | Full-time",
    position: "Management",
    standPoint: "Negotiable",
    remuneration: 400000,
    duration: "2 months ago",
    name: "Femtech",
    specialization: "Computer and Electronics",
    address: "Ilorin, Nigeria",
    logo: "/fem.png",
    summary: "Job Summary",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsum estfugit excepturi modi iste, quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum voluptatesmollitia quis nostrum quia in voluptatibus nonreiciendis architecto blanditiis numquam obcaecati laborum  sapiente provident!",
    qualification: "Diploma",
    level: "Mid level",
    experience: "4years",
  },
];
export const mainJobDetails = [
  {
    description: "Job Description and Requirements",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim hac massa consectetur vel et mauris. Ac mauris pulvinar eu urna ut ut. Tellus interdum duis proin morbi eget urna. Massa sed ut vulputate ullamcorper nulla sit. Id nulla mattis velit integer eget lacus ut lorem. Dolor ridiculus etiam feugiat risus ac dignissim. Odio tortor nulla consequat, adipiscing. Nibh aliquam praesent vel non ac. Phasellus laoreet felis velit amet pellentesque. Id ac facilisis purus aliquet sodales. Vel ipsum massa augue hendrerit in turpis sed. Accumsan eget et sed mauris.Ultrices suspendisse non phasellus ligula massa. Egestas aenean bibendum ultrices quis sagittis arcu. Pellentesque erat risus.",
    about: "About You",
    aboutDetails:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius et tortor, facilisis ut amet auctor. Quisque facilisi rhoncus ac placerat lectus congue nulla. Et adipiscing neque pretium vivamus adipiscing amet, elementum. Eu enim nisl aenean gravida turpis urna, fringilla. Non tempus tortor lobortis sit consectetur viverra in. Leo, lectus viverra bibendum arcu praesent aliquet aliquam. Sagittis morbi a cursus sollicitudin ornare ac vel egestas faucibus. Mauris feugiat aliquam eu tortor nibh ornare hac.",
    skills: "Required Skills and Competency",
    skillDetail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ",
    requirements: "Requirements",
    reqDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    safety: "Important Safety Tips ",
    safetyDetail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];
